### ISSUE TITLE
Update Docs: HamClock Configuration Notes

### ISSUE THREAD

**Issue by ChrisRomp** [ChrisRomp/hamclock-docker#11]
Using this issue to track some updates to README.md specific to configuring HamClock in Docker.

1. WiFi: Do not configure; this will use the Docker host network (see #10).
2. NTP: Configure time server to OS to skip time check (added in HamClock v3.05).

More in comments as I think of them.

**Comment by Aleziss** [comment]
I did test with the Synology integrated NTP server and it works instantly for me. I simply punched the IP address of the Synology and it sync instantly.

**Comment by ChrisRomp** [comment]
You can set the host to `OS` and it will use the host system time. That’ll be one of my notes. Of course if you have your own NTP server that’s fine, too.

I’m still thinking how much I want to write up, because I don’t want to duplicate the official manual or anything (and have to maintain it).

**Comment by Aleziss** [comment]
Understood, I was just reporting running your Docker on Synology NAS also connect to the integrated NTP service. I can only test under Synology Docker so this is why I just reported this. Thanks for your work !
