### ISSUE TITLE
Cannot set eastern position for map center

### ISSUE THREAD

**Issue by ChrisRomp** [ChrisRomp/hamclock-docker#12]
Seeing this in all architectures, cannot set the map center to `0E` or anything further east than `1W`. It will accept `0W` but returns to setup on next boot with `Err` in the field.

Local builds on Debian and Raspbian don't reproduce this error.

**Comment by ChrisRomp** [comment]
This issue will be fixed in a future release of HamClock. It can also be resolved in the container build if I change the Docker base image from Alpine to something like Debian Bookworm-slim, but that increases the container image size by ~150 MB. Not terrible, but if I can avoid that for now I prefer to.

I will leave this issue open for tracking until HamClock updates.

**Comment by ChrisRomp** [comment]
@Aleziss can you see if the 3.06 version allows you to set an Eastern position for map center? You can either update your HamClock in place, or pull the latest Docker image from this project's repo.

**Comment by Aleziss** [comment]
Problem seems to be fixed now with the map centering in v3.06. `0E` is working fine.

Thanks for the fix to both of you !
