### ISSUE TITLE
attempting to build 32 bit RasPi

### ISSUE THREAD

**Issue by Donner-Party** [ChrisRomp/hamclock-docker#27]
I'm attempting to docker compose on a Raspberry Pi 1 B running 32 bit Raspberry Pi OS Bullseye.

The PI is running headless (no monitor attached) and I'm working over SSH.

I installed docker using these instructions: https://docs.docker.com/engine/install/raspberry-pi-os/

docker compose stalls every time at this point:
     ![image](https://github.com/ChrisRomp/hamclock-docker/assets/44014054/7c18f22d-8d55-4f73-9d9a-0ab81a005ff6)

I have tried 1600x960 and 800x480 resolutions (thinking maybe no monitor attached was  the problem).

When it stalls, I also lose response on other SSH connections and I have to cold boot to get back in.

Any suggestions to get past this point? I have installed hamclock-docker on other 64 bit Pi and intel machines in the past with no problem.

**Comment by ChrisRomp** [comment]
All my Pis are headless. I've never tried to build it on anything that old. The fact that you have to reboot tells me something is going on beyond this container. That step in the build is running the compiler. I'm unsure of its compatibility on your hardware.

Have you tried installing HamClock directly on the Pi without Docker? I'm curious if it chokes at the same point. If it builds fine, well, problem solved but I would point to something going on in Docker at that point.

Also curious if other Docker containerized applications are able to run, especially anything that does a gcc build.

**Comment by ChrisRomp** [comment]
Another thought just occurred to me: In the Dockerfile on line 25 change the `make -j 4 ...` command to `make -j 1 ...`. Running four tasks in parallel might be a bit much for that CPU.

**Comment by Donner-Party** [comment]
Thanks! make -j 1 allowed it to complete, the CPU must have been overheating. And it only took 3 hours to complete.
![image](https://github.com/ChrisRomp/hamclock-docker/assets/44014054/534a8187-c0b1-4a5f-af30-375535b03a29)

However, I'm not able to reach it through my web browser and it always says it's restarting. Maybe I should just reserve Hamclock for machines with more horsepower.
![image](https://github.com/ChrisRomp/hamclock-docker/assets/44014054/6dbccaed-ba33-450c-9e7d-194b5544c056)

**Comment by ChrisRomp** [comment]
_Probably_ not a bad idea. 😅
