### ISSUE TITLE
Changing F to C

### ISSUE THREAD

**Issue by 9M2PJU** [ChrisRomp/hamclock-docker#34]
Hello OM,
How to change from temp F to C ?

**Comment by ChrisRomp** [comment]
Have you checked the HamClock manual? It looks like there's a `Units` option in the setup for Metric/Imperial. Change it to Metric to see if that changes the temperature to C.

https://www.clearskyinstitute.com/ham/HamClock/HamClockKey.pdf

**Comment by 9M2PJU** [comment]
I apologize for the inconvenience. I have solved the problems with the "Change F to C" option in HamClock.

**Comment by ChrisRomp** [comment]
Was it the `Units` setting? Posting your solution here can help others who may encounter the same issue.

**Comment by ChrisRomp** [comment]
Testing in my own instance, changing `Units` to `Metric` or `Imperial` did change the "DE Weather" pane temperature unit displayed.
