### ISSUE TITLE
ghcr.io/chrisromp/hamclock-docker:latest installation successful

### ISSUE THREAD

**Issue by mutzliputzli** [ChrisRomp/hamclock-docker#35]
[ghcr.io/chrisromp/hamclock-docker:latest](https://synologynas:9443/#!/2/docker/images/ghcr.io~2Fchrisromp~2Fhamclock-docker%3Alatest) works flawlessly on a Synology NAS under portainer.io installation. 

73 de DK6MR (dk6mr@darc.de).

**Comment by ChrisRomp** [comment]
Great feedback, thanks!
