### ISSUE TITLE
Not working in Unraid OS - can't pull data

### ISSUE THREAD

**Issue by strykarwolf** [ChrisRomp/hamclock-docker#39]
I have gotten the container working in Unraid but all I see is "No connection"

Logs show "LIVE: unknown GET live-ws"

See below for configuration. I have something running on 8080 but I also cannot get it to run on that port.

![image](https://github.com/user-attachments/assets/657a609d-80ef-47b1-ae81-5f9039770ce3)

**Comment by strykarwolf** [comment]
It is working now, apparently it does not work properly with Opera GX. I tried in Edge and Chrome and it's working fine

**Comment by ChrisRomp** [comment]
@strykarwolf REALLY appreciate you updating with the fix. Thanks!

**Comment by strykarwolf** [comment]
> @strykarwolf REALLY appreciate you updating with the fix. Thanks!

I work in IT so I now how frustrating it is to run into these issues and then just get "I fixed it" from 2 years ago. I would actually suggest getting this listed in the Unraid Community Applications (Forum linked below). I'm more than happy to assist with it and act as a tester if you need it on Unraid!!

https://forums.unraid.net/topic/87144-ca-application-policies-notes/
